# Generated by Django 5.1.10 on 2025-07-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("match_id", models.AutoField(primary_key=True, serialize=False)),
                ("match_name", models.CharField(max_length=255)),
                ("match_date", models.DateTimeField()),
                ("group_id", models.IntegerField()),
                ("stage_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "match_result_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("white_pins", models.IntegerField(blank=True, null=True)),
                ("penalty_pins", models.IntegerField(blank=True, null=True)),
                ("yellow_cards", models.IntegerField(blank=True, null=True)),
                ("red_cards", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("p1_position", models.IntegerField(blank=True, null=True)),
                ("p2_position", models.IntegerField(blank=True, null=True)),
                ("honor_point", models.IntegerField(blank=True, null=True)),
                ("point", models.IntegerField(blank=True, null=True)),
                ("completed_time_second", models.IntegerField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match.match"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match.team"
                    ),
                ),
            ],
        ),
    ]
