# Generated by Django 5.2.4 on 2025-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
